### ISSUE TITLE
How to reset the timer button

### ISSUE THREAD

**Issue by MartinMbae** [ajaynonstopio/timer_button#5]
I am using the timer button to request for OTP resending.

After the timer has come to 0 and the user presses the 'Resend OTP', is there a way to restart the timer counting again

**Comment by gerald-tetteh** [comment]
@MartinMbae @ajaynonstopio  created a pull request to add feature.

**Comment by ajaynonstopio** [comment]
Thanks, @gerald-tetteh. Part of 1.0.2
